// <auto-generated />
using ApiProdutos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProdutos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210722025120_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ApiProdutos.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Frutas frescas",
                            Estoque = 10,
                            Nome = "Laranja",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Frutas frescas",
                            Estoque = 10,
                            Nome = "Abacaxi",
                            Preco = 6.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Frutas frescas",
                            Estoque = 15,
                            Nome = "Uva",
                            Preco = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Frutas frescas",
                            Estoque = 5,
                            Nome = "Melancia",
                            Preco = 5.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
