// <auto-generated />
using ApiProdutos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiProdutos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210810001603_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ApiProdutos.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricaoFruta")
                        .HasColumnType("longtext");

                    b.Property<string>("fotoFruta")
                        .HasColumnType("longtext");

                    b.Property<string>("nomeFruta")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("qtdFruta")
                        .HasColumnType("int");

                    b.Property<decimal>("valorFruta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            descricaoFruta = "Frutas frescas",
                            fotoFruta = "",
                            nomeFruta = "Laranja",
                            qtdFruta = 10,
                            valorFruta = 4.50m
                        },
                        new
                        {
                            Id = 2,
                            descricaoFruta = "Frutas frescas",
                            fotoFruta = "",
                            nomeFruta = "Abacaxi",
                            qtdFruta = 10,
                            valorFruta = 6.00m
                        },
                        new
                        {
                            Id = 3,
                            descricaoFruta = "Frutas frescas",
                            fotoFruta = "",
                            nomeFruta = "Uva",
                            qtdFruta = 15,
                            valorFruta = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            descricaoFruta = "Frutas frescas",
                            fotoFruta = "",
                            nomeFruta = "Melancia",
                            qtdFruta = 5,
                            valorFruta = 5.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
